require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

# Load Nitrogen auto-linking script (generated by `npx nitrogen`)
load 'nitrogen/generated/ios/NitroGodot+autolinking.rb'

Pod::Spec.new do |s|
  s.name         = "react-native-nitro-godot"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => "13.0" }
  s.source       = { :git => package["repository"]["url"], :tag => "#{s.version}" }

  s.source_files = [
    "cpp/**/*.{h,hpp,c,cpp}",
    # iOS native view bridge + SDL/Godot stubs (cpp for C++ linkage)
    "ios/**/*.{h,m,mm,c,cpp}",
  ]

  # ── Godot engine iOS framework dependencies ────────────────────────────
  s.frameworks = [
    "Metal", "MetalKit", "MetalPerformanceShaders",
    "QuartzCore", "IOSurface",
    "AVFoundation", "CoreAudio",
    "AudioToolbox", "CoreHaptics", "CoreMotion",
    "GameController", "CoreVideo",
  ]

  # ── libgodot xcframework ─────────────────────────────────────────────────
  #
  # We cannot use SDK-conditional LIBRARY_SEARCH_PATHS or OTHER_LDFLAGS
  # in user_target_xcconfig because xcconfig SDK-conditional keys REPLACE
  # (not extend) the base value — $(inherited) only inherits from the
  # project level above, not from the same file's base key. This would
  # drop all pod library search paths (EXConstants, Expo, etc.).
  #
  # Instead, we use s.libraries to add -lgodot to the base OTHER_LDFLAGS,
  # and a script_phase to copy the correct platform slice into the pod's
  # own build output dir (already in base LIBRARY_SEARCH_PATHS).
  s.libraries = "godot"

  s.script_phase = {
    :name => "Copy libgodot for current platform",
    :execution_position => :before_compile,
    :script => <<~SCRIPT
      GODOT_XCFW="${PODS_TARGET_SRCROOT}/engine_build/output/ios/libgodot.xcframework"
      if [ "${PLATFORM_NAME}" = "iphonesimulator" ]; then
        SLICE_DIR="${GODOT_XCFW}/ios-arm64-simulator"
      else
        SLICE_DIR="${GODOT_XCFW}/ios-arm64"
      fi
      # The .a file has the full Godot build name (e.g. libgodot.ios.template_release.arm64.a)
      # so we glob for any libgodot*.a in the slice directory.
      SRC=$(find "$SLICE_DIR" -name 'libgodot*.a' -print -quit 2>/dev/null)
      if [ -z "$SRC" ]; then
        echo "warning: No libgodot*.a found in $SLICE_DIR — skipping copy"
        exit 0
      fi
      # CONFIGURATION_BUILD_DIR = PODS_CONFIGURATION_BUILD_DIR/react-native-nitro-godot
      # This is the exact directory in the app target's LIBRARY_SEARCH_PATHS.
      DST="${CONFIGURATION_BUILD_DIR}/libgodot.a"
      mkdir -p "${CONFIGURATION_BUILD_DIR}"
      if [ ! -f "$DST" ] || [ "$SRC" -nt "$DST" ]; then
        cp "$SRC" "$DST"
        # Strip Godot iOS app template objects that conflict with React Native:
        #   - app.ios.*.o              → defines _main (duplicate symbol with RN)
        #   - godot_app_delegate.*.o   → +[GDTApplicationDelegate load] hijacks app delegate
        #   - app_delegate_service.*.o → application:didFinishLaunchingWithOptions: calls
        #     apple_embedded_main() which creates a Godot instance before our code,
        #     causing "Only one Godot Instance may be created" error.
        # NOTE: apple_embedded.*.o references _OBJC_CLASS_$_GDTAppDelegateService,
        # so we provide a stub in ios/GDTAppDelegateServiceStub.m.
        # godot_view_renderer.*.o also stripped because it calls Main::setup2()
        # on first render frame, duplicating our GodotInstance::start() init.
        # We provide a no-op stub in ios/GDTViewRendererStub.m.
        for pattern in "app.ios." "godot_app_delegate." "app_delegate_service." "godot_view_renderer."; do
          OBJ=$(ar t "$DST" 2>/dev/null | grep "^${pattern}" | head -1)
          if [ -n "$OBJ" ]; then
            ar d "$DST" "$OBJ"
            echo "Stripped $OBJ from libgodot.a"
          fi
        done
        echo "Copied libgodot.a for ${PLATFORM_NAME} from $(basename $SRC)"
      fi
    SCRIPT
  }

  s.pod_target_xcconfig = {
    "HEADER_SEARCH_PATHS" => [
      "$(PODS_TARGET_SRCROOT)/engine_build/godot-src/core/extension",
      "$(PODS_TARGET_SRCROOT)/engine_build/godot-src",
      "$(PODS_TARGET_SRCROOT)/ios",
    ].join(" "),
    # NOTE: Do NOT add -ObjC here! It force-loads all object files from
    # libgodot.a (296K+ symbols), causing C++ vtable collisions with React.
    # libgodot is pure C/C++ (no ObjC categories) so -ObjC is unnecessary.
    # Suppress Godot's @deprecated comment warnings (gdextension_interface.gen.h)
    "WARNING_CFLAGS" => "-Wno-documentation-deprecated-sync",
  }

  # ── Nitrogen auto-linking: adds generated/shared and generated/ios sources,
  #    sets CLANG_CXX_LANGUAGE_STANDARD=c++20, adds NitroModules dependency
  add_nitrogen_files(s)
end
