#ifdef __ANDROID__
///
/// GodotOnLoad.cpp
/// JNI entry point for the NitroGodot Android module.
///
/// This file is the hand-authored companion to the Nitrogen-generated
/// NitroGodotOnLoad.cpp. It provides the JNI_OnLoad function that:
///   1. Initialises Facebook JNI helpers
///   2. Calls registerAllNatives() (Nitrogen's generated hook, which is
///      called from the autolinking cmake build)
///   3. Registers our hand-authored HybridGodotEngine into the Nitro registry
///   4. Stores the JavaVM* for later AAssetManager injection
///
/// iOS registration is handled below via __attribute__((constructor)).
///

#include <jni.h>
#include <fbjni/fbjni.h>
#include <NitroModules/HybridObjectRegistry.hpp>

// Nitrogen-generated registration hook
#include "../nitrogen/generated/android/NitroGodotOnLoad.hpp"

// Our hand-authored HybridObject implementation
#include "HybridGodotEngine.hpp"

using namespace margelo::nitro;
using namespace margelo::nitro::godot;

// Global JavaVM pointer — stored here for thread-safe JNI access.
// Used by HybridGodotEngine to inject AAssetManager before Godot init.
static JavaVM* g_jvm = nullptr;

JavaVM* NitroGodot_GetJavaVM() {
  return g_jvm;
}

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* /* reserved */) {
  g_jvm = vm;
  return facebook::jni::initialize(vm, []() {
    // 1. Register any JNI Kotlin/Java ↔ C++ bindings generated by Nitrogen
    //    (currently none for a pure-C++ module, but wired for future use)
    ::margelo::nitro::godot::registerAllNatives();

    // 2. Register HybridGodotEngine into the Nitro JSI object registry.
    //    JS can now call: NitroModules.createHybridObject('GodotEngine')
    HybridObjectRegistry::registerHybridObjectConstructor(
      "GodotEngine",
      []() -> std::shared_ptr<HybridObject> {
        return std::make_shared<HybridGodotEngine>();
      }
    );
  });
}
#endif // __ANDROID__

