/**
 * Stubs for missing symbols in libgodot.a's iOS build.
 *
 * SDL symbols use C linkage; Godot plugin symbols use C++ linkage.
 */

#include <stdbool.h>

// ── SDL stubs (C linkage) ──────────────────────────────────────────────
// libgodot.a's embedded SDL references these but the platform source
// files weren't included in the Godot iOS build.
extern "C" {

bool SDL_IsAppleTV(void) {
    return false;
}

bool SDL_IsIPad(void) {
    return false;
}

} // extern "C"

// ── Godot plugin stubs (C++ linkage) ───────────────────────────────────
// Normally generated by Godot's export process (see platform/ios/api/api.h).
// Since we embed Godot directly without Godot plugins, both are no-ops.
void godot_apple_embedded_plugins_initialize() {}
void godot_apple_embedded_plugins_deinitialize() {}
